name: NuGet Generation

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master



jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          source-url: https://nuget.pkg.github.com/rateitapp/index.json
        env:
          NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}        

      - name: Build solution and generate NuGet package
        run: dotnet pack "src\jmespath.net" -c Release -o out --no-dependencies -p:Version=1.0.126

      - name: Push generated package to GitHub registry
        run: dotnet nuget push "src\jmespath.net\out\jmespath.net.1.0.126.nupkg" --skip-duplicate --no-symbols true