name: NuGet Generation

on:
  push:
    branches:
      - master
  pull_request:
    types: [closed]
    branches:
      - master



jobs:
  build:
    runs-on: windows-latest
    name: Update NuGet package
    steps:

      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1

      - name: Build solution and generate NuGet package
        run: dotnet pack "src\jmespath.net" -c Release -o out --no-dependencies -p:Version=1.0.126

      - name: Push generated package to GitHub registry
        run: dotnet nuget push "out\*.nupkg"--source "https://nuget.pkg.github.com/rateitapp/index.json" --api-key "${{secrets.GITHUB_TOKEN}}" --skip-duplicate --no-symbols true 